//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 01:53:29 PM CET 
//


package ExternalPackages.org.hupo.psi.ms.traml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hupo.psi.ms.traml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TraML_QNAME = new QName("http://psi.hupo.org/ms/traml", "TraML");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hupo.psi.ms.traml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CompoundListType }
     * 
     */
    public CompoundListType createCompoundListType() {
        return new CompoundListType();
    }

    /**
     * Create an instance of {@link ProteinListType }
     * 
     */
    public ProteinListType createProteinListType() {
        return new ProteinListType();
    }

    /**
     * Create an instance of {@link CompoundType }
     * 
     */
    public CompoundType createCompoundType() {
        return new CompoundType();
    }

    /**
     * Create an instance of {@link CvListType }
     * 
     */
    public CvListType createCvListType() {
        return new CvListType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link PrecursorType }
     * 
     */
    public PrecursorType createPrecursorType() {
        return new PrecursorType();
    }

    /**
     * Create an instance of {@link PublicationType }
     * 
     */
    public PublicationType createPublicationType() {
        return new PublicationType();
    }

    /**
     * Create an instance of {@link SequenceType }
     * 
     */
    public SequenceType createSequenceType() {
        return new SequenceType();
    }

    /**
     * Create an instance of {@link UserParamType }
     * 
     */
    public UserParamType createUserParamType() {
        return new UserParamType();
    }

    /**
     * Create an instance of {@link SoftwareListType }
     * 
     */
    public SoftwareListType createSoftwareListType() {
        return new SoftwareListType();
    }

    /**
     * Create an instance of {@link CvType }
     * 
     */
    public CvType createCvType() {
        return new CvType();
    }

    /**
     * Create an instance of {@link ConfigurationListType }
     * 
     */
    public ConfigurationListType createConfigurationListType() {
        return new ConfigurationListType();
    }

    /**
     * Create an instance of {@link IntermediateProductType }
     * 
     */
    public IntermediateProductType createIntermediateProductType() {
        return new IntermediateProductType();
    }

    /**
     * Create an instance of {@link ProteinType }
     * 
     */
    public ProteinType createProteinType() {
        return new ProteinType();
    }

    /**
     * Create an instance of {@link TransitionListType }
     * 
     */
    public TransitionListType createTransitionListType() {
        return new TransitionListType();
    }

    /**
     * Create an instance of {@link ContactListType }
     * 
     */
    public ContactListType createContactListType() {
        return new ContactListType();
    }

    /**
     * Create an instance of {@link SourceFileType }
     * 
     */
    public SourceFileType createSourceFileType() {
        return new SourceFileType();
    }

    /**
     * Create an instance of {@link TransitionType }
     * 
     */
    public TransitionType createTransitionType() {
        return new TransitionType();
    }

    /**
     * Create an instance of {@link TargetType }
     * 
     */
    public TargetType createTargetType() {
        return new TargetType();
    }

    /**
     * Create an instance of {@link ValidationStatusType }
     * 
     */
    public ValidationStatusType createValidationStatusType() {
        return new ValidationStatusType();
    }

    /**
     * Create an instance of {@link EvidenceType }
     * 
     */
    public EvidenceType createEvidenceType() {
        return new EvidenceType();
    }

    /**
     * Create an instance of {@link TargetIncludeListType }
     * 
     */
    public TargetIncludeListType createTargetIncludeListType() {
        return new TargetIncludeListType();
    }

    /**
     * Create an instance of {@link RetentionTimeListType }
     * 
     */
    public RetentionTimeListType createRetentionTimeListType() {
        return new RetentionTimeListType();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link ConfigurationType }
     * 
     */
    public ConfigurationType createConfigurationType() {
        return new ConfigurationType();
    }

    /**
     * Create an instance of {@link CvParamType }
     * 
     */
    public CvParamType createCvParamType() {
        return new CvParamType();
    }

    /**
     * Create an instance of {@link SourceFileListType }
     * 
     */
    public SourceFileListType createSourceFileListType() {
        return new SourceFileListType();
    }

    /**
     * Create an instance of {@link SoftwareType }
     * 
     */
    public SoftwareType createSoftwareType() {
        return new SoftwareType();
    }

    /**
     * Create an instance of {@link ProteinRefType }
     * 
     */
    public ProteinRefType createProteinRefType() {
        return new ProteinRefType();
    }

    /**
     * Create an instance of {@link PublicationListType }
     * 
     */
    public PublicationListType createPublicationListType() {
        return new PublicationListType();
    }

    /**
     * Create an instance of {@link TargetListType }
     * 
     */
    public TargetListType createTargetListType() {
        return new TargetListType();
    }

    /**
     * Create an instance of {@link TraMLType }
     * 
     */
    public TraMLType createTraMLType() {
        return new TraMLType();
    }

    /**
     * Create an instance of {@link PeptideType }
     * 
     */
    public PeptideType createPeptideType() {
        return new PeptideType();
    }

    /**
     * Create an instance of {@link InstrumentListType }
     * 
     */
    public InstrumentListType createInstrumentListType() {
        return new InstrumentListType();
    }

    /**
     * Create an instance of {@link TargetExcludeListType }
     * 
     */
    public TargetExcludeListType createTargetExcludeListType() {
        return new TargetExcludeListType();
    }

    /**
     * Create an instance of {@link ModificationType }
     * 
     */
    public ModificationType createModificationType() {
        return new ModificationType();
    }

    /**
     * Create an instance of {@link PredictionType }
     * 
     */
    public PredictionType createPredictionType() {
        return new PredictionType();
    }

    /**
     * Create an instance of {@link InstrumentType }
     * 
     */
    public InstrumentType createInstrumentType() {
        return new InstrumentType();
    }

    /**
     * Create an instance of {@link InterpretationListType }
     * 
     */
    public InterpretationListType createInterpretationListType() {
        return new InterpretationListType();
    }

    /**
     * Create an instance of {@link InterpretationType }
     * 
     */
    public InterpretationType createInterpretationType() {
        return new InterpretationType();
    }

    /**
     * Create an instance of {@link RetentionTimeType }
     * 
     */
    public RetentionTimeType createRetentionTimeType() {
        return new RetentionTimeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TraMLType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://psi.hupo.org/ms/traml", name = "TraML")
    public JAXBElement<TraMLType> createTraML(TraMLType value) {
        return new JAXBElement<TraMLType>(_TraML_QNAME, TraMLType.class, null, value);
    }

}
