/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MSUmpire.GUI;

import MSUmpire.PeakDataStructure.PeakCurve;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author Chih-Chiang Tsou <chihchiang.tsou@gmail.com>
 */
public class PeakCurveViewer extends javax.swing.JFrame {
    private static final long serialVersionUID = 5938134696698208624L;

    /**
     * Creates new form PeakClusterViewer
     */
    PeakCurve peak = null;
    JFreeChart chart;

    public PeakCurveViewer() {
        initComponents();        
    }

    public void ShowPeakCluster(PeakCurve peak) {        
        chart = ChartDataConverter.createXICChart(peak);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
        jInternalFrame1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();

        setLayout(new java.awt.GridLayout(1, 0));

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        add(jInternalFrame1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables
}
