//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 01:53:29 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psi.hupo.org/ms/traml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ExtPackages.org.hupo.psi.ms.traml;
